name: ci

on: push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Baixar o repositório
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Instalar o Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12.1

            - name: Instalar o Poetry via pip
              run: pip install poetry

            - name: Instalar dependências com o Poetry
              run: poetry install

            - name: Test Docker is Working
              run: sudo docker run hello-world